cropmap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static
#from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cropmapapp/', include('cropmapapp.urls')),
    url(r'^', include('cropmapapp.urls', namespace='cropmapapp')),
    url('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cropmapapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cropmapapp'

urlpatterns = [
	
	#/cropmapapp/
	url(r'^$', views.home, name='home'),
	#/cropmapapp/
	url(r'^about/$', views.about, name='about'),
	#/cropmapapp/
	url(r'^image/$', views.index, name='index'),
	#/cropmapapp/712/
	url(r'^image/(?P<image_id>[0-9]+)/$', views.detail, name='detail'),
	#/cropmapapp/image/add
	url(r'^image/add_image/$',views.image_add, name='image-add'),
	#/cropmapapp/image/2/
	# url(r'^image/(?P<image_id>[0-9]+)/$',views.ImageUpdate, name='image-update'),
	#/cropmapapp/image/2/delete
	url(r'^image/(?P<image_id>[0-9]+)/delete_image/$',views.image_delete, name='image-delete'),



	# test algorithm
	url(r'^image/test/(?P<image_id>[0-9]+)/$',views.test_algorithm, name='test-algorithm'), 
	# test algorithm - croppingdata
	url(r'^croppingdata/(?P<image_id>[0-9]+)/test/(?P<data_id>[0-9]+)/$',views.test_algorithm_data, name='test-algorithm-data'), 



	#/cropping/
	url(r'^cropping/$', views.cropping, name='cropping'),
	#/cropping/712/
	url(r'^cropping/(?P<image_id>[0-9]+)/$', views.croppingdetail, name='croppingdetail'),
	#/cropping/add
	url(r'^cropping/add-cropping/$',views.cropping_add, name='cropping-add'),
	#/cropping/2/delete
	url(r'^cropping/(?P<image_id>[0-9]+)/delete-data/$',views.croppingimage_delete, name='croppingimage-delete'),

	#/cropping/compare/712/
	url(r'^cropping/compare/(?P<image_id>[0-9]+)/$', views.compare, name='compare'),

	
	#/cropping/712/
	url(r'^croppingdata/(?P<data_id>[0-9]+)/$', views.croppingdatadetail, name='croppingdatadetail'),
	#/croppingdata/add
	url(r'^(?P<image_id>[0-9]+)/add-data/$',views.croppingdata_add, name='data-add'),
	#/cropping/2/delete
	url(r'^cropping/(?P<image_id>[0-9]+)/delete-croppingdata/(?P<data_id>[0-9]+)/$',views.croppingdata_delete, name='croppingdata-delete'),


	#Register
	url(r'^register/$', views.register, name='register'),
	#Login_User
	url(r'^login_user/$', views.login_user, name='login_user'),
	#Logout_User
	url(r'^logout_user/$', views.logout_user, name='logout_user'),


	# confirm password
	url(r'^password_reset/$',auth_views.password_reset,name='password_reset'),
	url(r'^password_reset/done/$',auth_views.password_reset_done,name='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Z-a-z]{1,20})/$',auth_views.password_reset_confirm,name='password_reset_confirm'),
	url(r'^reset/done/$',auth_views.password_reset_complete,name='password_reset_complete'),
	# url(r'^password_reset/$',auth_views.password_reset,{'template_name':'password_reset_form.html'}),

	url(r'^accounts/login/$',views.login_user, name='login_user'),

	#/print
	url(r'^print/(?P<image_id>[0-9]+)/$', views.print_data, name='print-data'),

	#/print-comparison
	url(r'^printcomparison/(?P<image_id>[0-9]+)/$', views.print_comparison, name='print-comparison')

]	

cropmapapp/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

class Image(models.Model):
	user = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
	image_name = models.CharField(max_length = 1000)
	image_description = models.CharField(max_length = 2000)
	image_raw = models.FileField()
	processed = models.BooleanField(default=False)

	# def get_absolute_url(self):
	# 	return reverse('cropmapapp:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return str(self.image_raw)

class Data(models.Model):
	image = models.ForeignKey(Image, on_delete = models.CASCADE)
	raw = models.CharField(max_length = 1000)
	ndvi = models.CharField(max_length = 1000)
	osavi = models.CharField(max_length = 1000)
	ndvi_4x4 = models.CharField(max_length = 1000)
	osavi_4x4 = models.CharField(max_length = 1000)
	graph = models.CharField(max_length = 1000)
	ndvipiegraph = models.CharField(max_length = 1000)
	osavipiegraph = models.CharField(max_length = 1000)

	def __str__(self):
		return self.raw

class CroppingImage(models.Model):
	user = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
	surveying_area = models.CharField(max_length = 1000)
	address = models.CharField(max_length = 1000)
	land_description = models.CharField(max_length = 2000)
	image_raw = models.FileField()

	# def get_absolute_url(self):
	# 	return reverse('cropmapapp:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.surveying_area
	
		
class CroppingData(models.Model):
	image = models.ForeignKey(CroppingImage, on_delete = models.CASCADE)
	cropping = models.FileField()
	croppingdate = models.DateField()
	description = models.CharField(max_length = 2000)
	processed = models.BooleanField(default=False)

	def __str__(self):
		return str(self.cropping)


class CroppingDataDetail(models.Model):
	image = models.ForeignKey(CroppingData, on_delete = models.CASCADE)
	raw = models.CharField(max_length = 1000)
	ndvi = models.CharField(max_length = 1000)
	osavi = models.CharField(max_length = 1000)
	ndvi_4x4 = models.CharField(max_length = 1000)
	osavi_4x4 = models.CharField(max_length = 1000)
	graph = models.CharField(max_length = 1000)
	ndvipiegraph = models.CharField(max_length = 1000)
	osavipiegraph = models.CharField(max_length = 1000)

	def __str__(self):
		return self.raw

class Comparison(models.Model):
	image = models.ForeignKey(CroppingImage, on_delete = models.CASCADE)
	raw = models.CharField(max_length = 1000)
	croppingdate =models.DateField()
	description = models.CharField(max_length = 2000)
	graph = models.CharField(max_length = 1000)
	ndvipiegraph = models.CharField(max_length = 1000)
	osavipiegraph = models.CharField(max_length = 1000)
	croppingdata = models.CharField(max_length = 1000)

	def __str__(self):
		return str(self.image)
	
		

cropmapapp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import ImageForm, CroppingForm, CroppingDataForm, UserForm, DataForm, CroppingDataDetailForm, ComparisonForm
from .models import Image, CroppingImage, CroppingData, Data, CroppingDataDetail, Comparison
from django.contrib import auth

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Image Add
def image_add(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        form = ImageForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.image_raw = request.FILES['image_raw']
            file_type = image.image_raw.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'image': image,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'cropmapapp/image_form.html', context)
            image.save()
            images = Image.objects.filter(user=request.user)
            return render(request, 'cropmapapp/index.html', {'images': images})
        context = {
            "form": form,
        }
        return render(request, 'cropmapapp/image_form.html', context)


# Image Delete
def image_delete(request, image_id):
    image = Image.objects.get(pk=image_id)
    image.delete()
    images = Image.objects.filter(user=request.user)
    return render(request, 'cropmapapp/index.html', {'images': images})


# Cropping Image
def cropping(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        images = CroppingImage.objects.filter(user=request.user)
        query = request.GET.get("q")
        if query:
            images = images.filter(
                Q(surveying_area__icontains=query) |
                Q(image_raw__icontains=query) |
                Q(address__icontains=query) |
                Q(land_description__icontains=query)
            ).distinct()
            return render(request, 'cropmapapp/cropping.html', {
                'images': images,
                'croppings': croppings,
            })
        else:
            return render(request, 'cropmapapp/cropping.html', {'images': images})


# Cropping Detail
def croppingdetail(request, image_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        image = get_object_or_404(CroppingImage, pk=image_id)

        return render(request, 'cropmapapp/croppingdetail.html', {'image': image, 'user': user})



# Cropping Data Detail
def croppingdatadetail(request, data_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        croppingdata = get_object_or_404(CroppingData, pk=data_id)
        return render(request, 'cropmapapp/croppingdatadetail.html', {'croppingdata': croppingdata, 'user': user})


# Compare
def compare(request, image_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        image = get_object_or_404(CroppingImage, pk=image_id)

        compare = image.comparison_set.all()

        return render(request, 'cropmapapp/comparison.html', {'image': image, 'compare':compare, 'user': user})


# Print Compare
def print_comparison(request, image_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        image = get_object_or_404(CroppingImage, pk=image_id)

        compare = image.comparison_set.all()

        return render(request, 'cropmapapp/print-comparison.html', {'image': image, 'compare':compare, 'user': user})


# Cropping Image Add
def cropping_add(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        form = CroppingForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.image_raw = request.FILES['image_raw']
            file_type = image.image_raw.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'image': image,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'cropmapapp/croppingimage_form.html', context)
            image.save()
            return render(request, 'cropmapapp/croppingdetail.html', {'image': image})
        context = {
            "form": form,
        }
        return render(request, 'cropmapapp/croppingimage_form.html', context)


# Cropping Image Add
def croppingdata_add(request, image_id):
    form = CroppingDataForm(request.POST or None, request.FILES or None)
    croppingimage = get_object_or_404(CroppingImage, pk=image_id)

    if form.is_valid():
        croppingdata = form.save(commit=False)
        croppingdata.image = croppingimage
        croppingdata.save()
        return render(request, 'cropmapapp/croppingdetail.html', {'image':croppingimage}) 
    context = {
        'image':croppingimage,
        'form':form,
    }
    return render(request, 'cropmapapp/croppingdata_form.html', context)


# Cropping Image Delete
def croppingimage_delete(request, image_id):
    cropping = CroppingImage.objects.get(pk=image_id)
    cropping.delete()
    cropping = CroppingImage.objects.filter(user=request.user)
    return render(request, 'cropmapapp/cropping.html', {'images': cropping})


# Cropping Data Delete
def croppingdata_delete(request, image_id, data_id):
    croppingimage = get_object_or_404(CroppingImage, pk=image_id)
    croppingdata = CroppingData.objects.get(pk=data_id)
    croppingdata.delete()

    compare = Comparison.objects.all()
    
    compare_data = ''
    
    for a in compare:
        if a.croppingdata == croppingdata.cropping:
            compare_data = a.croppingdata

    to_delete = Comparison.objects.filter(croppingdata=compare_data)
    to_delete.delete()

    return render(request, 'cropmapapp/croppingdetail.html', {'image': croppingimage})


# Index
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        images = Image.objects.filter(user=request.user)
        query = request.GET.get("q")
        if query:
            images = images.filter(
                Q(image_name__icontains=query) |
                Q(image_raw__icontains=query) |
                Q(image_description__icontains=query)
            ).distinct()
            return render(request, 'cropmapapp/index.html', {
                'images': images,
            })
        else:
            return render(request, 'cropmapapp/index.html', {'images': images})

# Home
def home(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        return render(request, 'cropmapapp/home.html')


# About
def about(request):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        return render(request, 'cropmapapp/about.html')


# Image Data
def detail(request, image_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        image = get_object_or_404(Image, pk=image_id)
        return render(request, 'cropmapapp/detail.html', {'image': image, 'user': user})

# Image Data
def print_data(request, image_id):
    if not request.user.is_authenticated:
        return render(request, 'cropmapapp/login.html')
    else:
        user = request.user
        image = get_object_or_404(Image, pk=image_id)
        return render(request, 'cropmapapp/print-data.html', {'image': image, 'user': user})


# Test_Algorithm
def test_algorithm(request, image_id):
    image = get_object_or_404(Image, pk=image_id)

    import cv2
    import numpy as np
    #import tkinter as tk
    import matplotlib
    matplotlib.use('Agg')
    from matplotlib import pyplot as plt
    import os
    import matplotlib.patches as mpathches

    np.seterr(divide = 'ignore', invalid = 'ignore')
    #root = tk.Tk()
    # def retrieve_input():
    images = str(image.image_raw)
    print(images)
    # inputValue = textBox.get("1.0","end-1c")
    filename=os.path.basename('./media/' + images)
    img1 = cv2.imread('./media/' + filename)
    # legend = cv2.imread('./media/legend.jpg')

    #RESIZE
    resized_image = img1[0:512, 0:512]

    #CONVERT TO HSV
    hsvColor = cv2.cvtColor(resized_image, cv2.COLOR_BGR2HSV)
    hsvColor1 = cv2.cvtColor(resized_image, cv2.COLOR_BGR2HSV)
    rgbColor = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB)
    rgbColor1 = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB) 
    rgbColor2 = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB) 
    rgbColor3 = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB) 


    #HOW BEAUTIFUL IS BEAUTIFUL
    #RED
    SOIL_MIN = np.array([160, 50, 200])
    SOIL_MAX = np.array([180, 145, 255])

    GRAY_MIN = np.array([0, 40, 25])
    GRAY_MAX = np.array([140, 280, 255])

    #NIR
    PINK_MIN = np.array([140, 100, 0])
    PINK_MAX = np.array([180, 255, 255])

    DARK_MIN = np.array([0, 85, 130])
    DARK_MAX = np.array([10, 255, 230])



    # Variables for Computing Percentage
    #NDVI
    ndvi_125 = 0

cropmapapp/templates/cropmapapp/base.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  	<title>{% block title %}CropMap{% endblock %}</title>
  	{% load staticfiles %}
  	<link rel="shortcut icon" type="image/png" href="{%  static 'cropmapapp/img/cropmaplogo.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/style.css' %}">
	<script src="{% static 'cropmapapp/js/bootstrap.js' %}"></script>
	<script src="{% static 'cropmapapp/js/jquery.js' %}"></script>
	<script src="{% static 'cropmapapp/js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/font-awesome.min.css' %}">
 </head>
 <body>
  	<div class="wrapper">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				
				<!-- Header -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand title" href="{% url 'cropmapapp:home' %}"><img src="{%  static 'cropmapapp/img/cropmaplogo.png' %}" class="img-logo-nav"><b class="title-base">CropMap</b></a>
				</div>

				<!-- Items -->
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li class="{% block images %}{% endblock %}">
							<a href="{% url 'cropmapapp:index' %}" class="link">
								<span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp; IMAGES
							</a>
						</li>
						<li class="{% block cropping %} {% endblock %}">
							<a href="{% url 'cropmapapp:cropping' %}" class="link">
								<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; CROPPINGS
							</a>
						</li>
					</ul>
					{% block searchbar %}
					<form class="navbar-form navbar-left" role="search" method="get" action="{% block search_in_index %} {% url 'cropmapapp:index' %} {% endblock %}">
						<div class="form-group">
							<input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
						</div>
						<button type="submit" class="btn btn-default">SEARCH</button>
					</form>
					{% endblock %}
					<ul class="nav navbar-nav navbar-right">
						{% block hideadd %}
						<li class="#">
							<a href="{% block addimage %} {% url 'cropmapapp:image-add' %} {% endblock %}" class="link">
								<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; {% block addmenu %} ADD IMAGE {% endblock %}
							</a>
						</li>
						{% endblock %}
						<li class="{% block about %} {% endblock %}">
							<a href="{% url 'cropmapapp:about' %}" class="link">
								<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; ABOUT
							</a>
						</li>
						<li class="#">
							<a href="#" class="link">
								<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {{ user }}
							</a>
						</li>
						<li class="#">
							<a href="{% url 'cropmapapp:logout_user' %}" class="link">
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LOGOUT
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</div>
	
	<div class="container-fluid image-body">
		{% block body %}
		{% endblock %}
	</div>
</body>
</html>

cropmapapp/templates/cropmapapp/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}CropMap{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'cropmapapp/img/cropmaplogo.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/style.css' %}">
    <script src="{% static 'cropmapapp/js/bootstrap.js' %}"></script>
    <script src="{% static 'cropmapapp/js/jquery.js' %}"></script>
    <script src="{% static 'cropmapapp/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cropmapapp/css/font-awesome.min.css' %}">
</head>
<body  class="image-body">
    <div class="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">

                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand title" href="{% url 'cropmapapp:home' %}"><img src="{%  static 'cropmapapp/img/cropmaplogo.png' %}" class="img-logo-nav"><b class="title-base">CropMap</b></a>
                </div>

                <!-- Items -->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <li class="{% block register_active %}{% endblock %}"><a href="{% url 'cropmapapp:register' %}">REGISTER</a></li>
                        <li class="{% block login_active %}{% endblock %}"><a href="{% url 'cropmapapp:login_user' %}">LOG IN</a></li>
                    </ul>
                </div>

            </div>
        </nav>
    </div>

    <style type="text/css">
        .image-body{
            background-image: url({% static 'cropmapapp/img/bg2-dark.jpg' %}); 
        }
    </style>

    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

cropmapapp/templates/cropmapapp/croppingdetail.html
{% extends 'cropmapapp/base.html' %}
{% block title %}CropMap | Cropping Data{% endblock %}
{% block images %} {% endblock %}
{% block addimage %} {% url 'cropmapapp:cropping-add'  %} {% endblock %}
{% block cropping %}active{% endblock %}
{% block addmenu %} ADD CROPPING {% endblock %}


{% block body %}
	<div class="row">
		<div class="col-md-2 detail-body">	
			<div class="need-padding popup">
				<div class="row">
					<div class="col-xs-12 center">
						<img src="/media/{{ image.image_raw }}" class="small-image-comparison">
						<h4>{{ image.surveying_area }}</h4>
	           			<p>{{ image.address }}<br>{{ image.land_description }}</p>
		            </div> 
	            </div>  	
			</div>
		</div>
		
		<div class="col-md-10">
			<div class="page-header">
				<h2>Cropping Image Data <a href="{% url 'cropmapapp:data-add' image.id %}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Add Cropping Data</a> &nbsp;<a href="{% url 'cropmapapp:compare' image.id %}" class="btn btn-success"><span class="glyphicon glyphicon-list-alt"></span> &nbsp;View Comparison</a>
				</h2>
			
			</div>
			<div class="row">
				{% for data in image.croppingdata_set.all %}
					<div class="col-sm-3">
						<div class="panel panel-default popup">
							<div class="panel-body center">
								<a href="{% url 'cropmapapp:croppingdatadetail' data.id %}"><img src="/media/{{ data.cropping }}" class="image-width output-img"></a>
							</div>
							<div class="panel-footer">
								<div class="form-group">
									<h4>{{ data.croppingdate }}</h4>
									<p>
										{{ data.description }}
									</p>

									<a href="{% if data.processed %} {% url 'cropmapapp:index' %} {% else %} {% url 'cropmapapp:test-algorithm-data' image.id data.id %} {% endif %}" class="{% if data.processed %} processed {% else %} btn-success {% endif %}">{% if data.processed %}<button class="btn btn-default btn-sm disabled"><span class="glyphicon glyphicon-ok"></span></button>{% else %}<button class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal" data-backdrop="static" data-keyboard="false">Process Image </button>{% endif %}</a>

									<a href="{% url 'cropmapapp:croppingdatadetail' data.id %}" class="btn btn-default btn-sm">View Details</a>

									<form action="{% url 'cropmapapp:croppingdata-delete' image.id data.id %}" method="post" style="display: inline;">
										{% csrf_token %}
										<button class="btn btn-default btn-sm">
											<span class="glyphicon glyphicon-trash"></span>
										</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade verdana" id="myModal" tabindex="-1" role="dialog">
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header ">
	        		<h4 class="modal-title"><span class="glyphicon glyphicon-time"></span> Processing Image...</h4>
	      		</div>
	      		<div class="modal-body center-block">
	          		<div class="form-group">
	            		<p>Please wait for few minutes while processing...</p>
			        	<div class="progress">
						  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
						    <span class="sr-only">45% Complete</span>
						  </div>
						</div>
	      			</div>
	      		</div>
	    	</div>
	  	</div>
	</div>
	
	<script>
		$('#myModal').on('shown.bs.modal', function () {
		    var progress = setInterval(function() {
		    var $bar = $('.bar');

		    if ($bar.width()==600) {
		        // complete
		        clearInterval(progress);
		        $('.progress').removeClass('active');
		        $('#myModal').modal('hide');
		        $bar.width(0);
		    } else {
		        // perform processing logic here
		        $bar.width($bar.width()+3);
		    }
		}, 1000);
		})
	</script>
{% endblock %}

cropmapapp/templates/cropmapapp/form-template.html
{% for field in form %}
	 <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-3" for="data">{{ field.label_tag }}</label>
        <div class="col-sm-9">{{ field }}</div>
    </div>
{% endfor %}